### ISSUE TITLE
Problem using scikit-network on windows in PyCharm

### ISSUE THREAD

**Issue by moissinac** [sknetwork-team/scikit-network#443]
* scikit-network version: 0.19.3
* Python version: 3.6
* Operating System: windows 10 64 bits

### Description

Do a simple test in debug mode under the PyCharm IDE

### What I Did
Succesfully install scikit-network (checked in console)
My test code in PyCharm:

import sknetwork as skn
graph = skn.data.karate_club(metadata=True)

Error message
C:\outils\Python\Python36\python.exe "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\pydevd.py" --cmd-line --multiproc --qt-support=auto --client 127.0.0.1 --port 55127 --file C:/wamp64/www/givingsense.eu/datamusee/python/datamusee/trials/trialScikitNetwork.py
pydev debugger: process 1888 is connecting

Connected to pydev debugger (build 192.7142.79)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\pydevd.py", line 2108, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\pydevd.py", line 2099, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\pydevd.py", line 1408, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/wamp64/www/givingsense.eu/datamusee/python/datamusee/trials/trialScikitNetwork.py", line 1, in <module>
    import sknetwork as skn
  File "C:\outils\Python\Python36\lib\site-packages\sknetwork\__init__.py", line 9, in <module>
    import sknetwork.topology
  File "C:\outils\Python\Python36\lib\site-packages\sknetwork\topology\__init__.py", line 2, in <module>
    from sknetwork.topology.kcliques import Cliques
  File "sknetwork\topology\kcliques.pyx", line 11, in init sknetwork.topology.kcliques
  File "sknetwork\topology\kcliques.pyx", line 11, in __Pyx_PyMODINIT_FUNC PyInit_kcliques(void)
TypeError: 'NoneType' object is not callable

Process finished with exit code 1

**Comment by QLutz** [comment]
Hello,

Thanks for your interest for our package.

Sadly, this issue does not stem from scikit-network but from Pycharm not having a debugger for Cython. It has been a [long-time request](https://youtrack.jetbrains.com/issue/PY-9476?_ga=2.154305919.658754338.1600843872-204496230.1600843872) from the users to have this particular feature and will likely not be implemented soon.

However, as long as you are not using Cython in your tests, you can still use the standard Python debugger. To do so, you can use [configurations](https://github.com/sknetwork-team/scikit-network/wiki/Dev-tips#test-configuration) for testing pure-Python modules only for instance.

Also note that, when using scikit-network from sources, you should [generate and compile](https://github.com/sknetwork-team/scikit-network/wiki/Cython-specifics#generating-c-code-with-cython-and-compiling-it) the corresponding C++ code if you want to run the whole test suite.

**Comment by moissinac** [comment]
I can't easily know if a method of scikit-network uses Cython or not. So, you seem to say that I can't use scikit-network in Pycharm with a simple pip install. I've tried your link about 'configurations', but it seems to apply only for developers of scikit-network (and i get the same error with my source (2 lines, just loading a dataset)
Is there a mean to view Cython modules as 'opaque' modules (like call to system functions are not accessible for debuging)

**Comment by moissinac** [comment]
An update to Pycharm solves the problem...
