### ISSUE TITLE
Cannot load package

### ISSUE THREAD

**Issue by jhammarstedt** [sknetwork-team/scikit-network#523]
* scikit-network version: 0.25
* Python version: 3.9

### Description
Importing sknetwork yields:

```
>>> import sknetwork
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/new1/lib/python3.9/site-packages/sknetwork/__init__.py", line 9, in <module>
    import sknetwork.topology
  File "/opt/conda/envs/new1/lib/python3.9/site-packages/sknetwork/topology/__init__.py", line 2, in <module>
    from sknetwork.topology.kcliques import Cliques
  File "sknetwork/topology/kcliques.pyx", line 1, in init sknetwork.topology.kcliques
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
Any ideas what may cause this?

**Comment by jhammarstedt** [comment]
Oh it just turned out to just be a numpy error, closing this.

**Comment by KeironO** [comment]
@jhammarstedt how was you able to fix this?

**Comment by KeironO** [comment]
Ok, so if you run:

pip install -I --upgrade numpy --force

It should fix it.

**Comment by jhammarstedt** [comment]
Yes I just upgraded numpy and then it worked fine! @KeironO
